apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: no-affinity-
  labels:
    app: no-affinity
spec:
  replicas: 200
  selector:
    matchLabels:
      app: no-affinity
  template:
    metadata:
      labels:
        app: no-affinity
    spec:
      imagePullSecrets:
      - name: docker-credentials
      containers:
      - name: perf-1
        image: busybox
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 2419200; done;" ]


