apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: dep-spread-
spec:
  selector:
    matchLabels:
      app: store
  replicas: 2
  template:
    metadata:
      labels:
        app: store
    spec:
      imagePullSecrets:
      - name: docker-credentials
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - store
            namespaces:
            - default
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: store
        image: busybox
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 2419200; done;" ]
